FROM maven:3.8.5-openjdk-18 AS build
COPY ./ /app
WORKDIR /app
RUN mvn --show-version --update-snapshots --batch-mode clean package

FROM openjdk:18-jdk-alpine3.14
RUN mkdir /app
WORKDIR /app
COPY --from=build ./app/api/target/order-api-1.2.0-SNAPSHOT.jar /app
EXPOSE 8080
CMD ["java", "-jar", "order-api-1.2.0-SNAPSHOT.jar"]