kumuluzee:
  name: order-service
  env:
    name: dev
  version: 1.3.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/OrderMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/order-metadata
      username: dbuser
      password: postgres
      pool:
        max-size: 1
  health:
    servlet:
      mapping: /health
      enabled: true
    checks:
      data-source-health-check:
        type: both
        jndi-name: jdbc/OrderMetadataDS
      disk-space-health-check:
        type: both
        threshold: 10000000 # 10MB
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="deliveryman-logging">
                    <Appenders>
                        <Console name="console" target="SYSTEM_OUT">
                            <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                        </Console>
                        <Socket name="logstash" host="90ac9cf8-f6c0-481f-af1b-ee7efd023607-ls.logit.io" port="15163" protocol="udp">
                            <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                        </Socket>
                    </Appenders>
                    <Loggers>
                      <Logger name="si.fri.rso.domen2.order.api.v1.resources.OrderMetadataResource" level="all" additivity="false">
                        <AppenderRef ref="logstash"/>
                      </Logger>
                      <Logger name="si.fri.rso.domen2.order.api.v1.resources.ExternalTest" level="all" additivity="false">
                        <AppenderRef ref="logstash"/>
                      </Logger>
                      <Logger name="si.fri.rso.domen2.order.services.beans.OrderMetadataBean" level="all" additivity="false">
                        <AppenderRef ref="logstash"/>
                      </Logger>
                      <Logger name="si.fri.rso.domen2.order.services.clients.RadarClient" level="all" additivity="false">
                        <AppenderRef ref="logstash"/>
                      </Logger>
                      <Logger name="si.fri.rso.domen2.order.services.clients.DeliverymanClient" level="all" additivity="false">
                        <AppenderRef ref="logstash"/>
                      </Logger>
                      <Logger name="si.fri.rso.domen2.order.services.clients.RestaurantClient" level="all" additivity="false">
                        <AppenderRef ref="logstash"/>
                      </Logger>
                      <Logger name="si.fri.rso.domen2.order.services.clients.ClientClient" level="all" additivity="false">
                        <AppenderRef ref="logstash"/>
                      </Logger>
                      <!-- Default logger -->
                      <Root level="all">
                          <AppenderRef ref="console" level="info" />
                      </Root>
                    </Loggers>
                  </Configuration>'
  dev:
    scan-libraries:
      - order-services
      - order-models
      - order-lib
  cors-filter:
    servlet:
     allow-origin: "*"

rest-properties:
  maintenance-mode: false
  broken: false

external-services:
  radar:
    url: https://api.radar.io
    secret: prj_test_pk_0f864f625ddff3adb7949f7a2a8c9f2a3a001c72
  deliveryman:
    url: http://20.75.162.98/deliveryman
  restaurant:
    url: http://20.75.162.98/restaurant
  client:
    url: http://20.75.162.98/client
